### PR TITLE
Added Arch Linux to dowload list

### LINKED ISSUE #7: Add Arch Linux
htop already exists in [Arch Linux Packages](https://archlinux.org/packages/extra/x86_64/htop/), but this is not mentioned in the htop's [download's section](https://htop.dev/downloads.html)

I think it is worth explicitly mentioning it

### PR DESCRIPTION
**Pull request by ghost**
Fixes #7

### CODE REVIEW

**Comment by fasterit** [comment]
Could you add a thanks line, like the other distro packagers have?
Christian Hesse seems to be the packager acc. to https://archlinux.org/packages/extra/x86_64/htop/

**Comment by BenBE** [comment]
There should also be a change to `download.haml` in the root directory adding this change.

**Comment by ghost** [comment]
Done

**Comment by BenBE** [comment]
Mind to squash things into one commit?

LGTM otherwise …

**Comment by ghost** [comment]
ugh, might have a problem here.
Closing it for now and opening a new one

**Pull request closed without merging**
