### PR TITLE
README.md

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by fasterit** [comment]
This is a bit too thin for the readme. You could add more useful information, e.g. link to github pages instructions and tell people how to check a patch they make to be rendered correctly.

**Review by ghost — COMMENTED** [review]
htop-dev.github.io

**Comment by ghost** [comment]
Nie som si istý či mi to pomôže dosadiť zip app určené na root bez root v totožnej funkcionalite

**Comment by fasterit** [comment]
spam

**Pull request closed without merging**
